main--- 
components: 
  schemas: 

    # This is a defintion of a person.
    Person:
      $ref: "https://raw.githubusercontent.com/lonelygunter/Smart-library-EMR/main/models/models.yaml#/Person"
    
    # This is a defintion of a book.
    Book:
      $ref: "https://raw.githubusercontent.com/lonelygunter/Smart-library-EMR/main/models/models.yaml#/Book"
      
    # This is a defintion of a library.
    Library:
      $ref: "https://raw.githubusercontent.com/lonelygunter/Smart-library-EMR/main/models/models.yaml#/Library"
      
    # This is a defintion of a category.
    Category:
      $ref: "https://raw.githubusercontent.com/lonelygunter/Smart-library-EMR/main/models/models.yaml#/Category"

    Device: 
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/device.yaml#/Device"
    
    SupportedProtocol: 
      $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/device.yaml#/SupportedProtocol"

info: 
  description: "Base Model Definitions from Smart Data Models"
  title: Baseline Models
  version: "1.0.0"
openapi: "3.0.0"


# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object

