--- 
components: 
  schemas: 

    # This is a defintion of a person.
    Person:
      $ref: "https://github.com/lonelygunter/Smart-library-EMR/tree/SmartDataModels/SmartDataModels/Person/schema.org.yaml#/Person"
info: 
  description: "Base Model Definitions from Smart Data Models"
  title: Baseline Models
  version: "1.0.0"
openapi: "3.0.0"


# These paths are merely representative.
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          description:  OK
          content: 
            application/ld+json: 
              schema: 
                type: object
